name: Publish The Docker image to the GHCR
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Dockerfile labels
        id: extract_labels
        run: |
          LABELS=$(docker inspect --format='{{json .Config.Labels}}' Dockerfile | jq -c 'to_entries[] | .key + "=" + .value')
          echo "::set-output name=labels::$LABELS"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name }}
          tags: ghcr.io/${{ github.actor }}/${{ github.repository }}:${{ github.ref_name }}
          labels: ${{ steps.extract_labels.outputs.labels }}
