name: Publish Docker image to GHCR
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/tldr-lint:latest
            ghcr.io/${{ github.actor }}/tldr-lint:${{ github.ref_name }}
          labels: |
            org.opencontainers.image.title="tldr-lint"
            org.opencontainers.image.description="This image contains the latest version \
            of the tldr-lint package preinstalled."
            org.opencontainers.image.source="https://github.com/tldr-pages/tldr-lint"
            org.opencontainers.image.authors="tldr-pages maintainers and contributors"
            org.opencontainers.image.vendor="tldr.sh"
            org.opencontainers.image.licenses="MIT"
